import React from 'react'

export default function About() {
	return (
		<div className='about-container'>
			<ul className='about'>
				<br />
				<li>
					This app was created as a project for my General Assembly software engineering class, but it was inspired by a real life experience - thru hiking the Colorado Trail in the summer of 2022, which was the trip of a lifetime. I hiked 486 miles, met some amazing people, saw some inspiring landscapes, and experienced some wild weather. But I never kept a journal, so I thought it would be cool to create this app as a tool to help me remember moments along the way from my photos.
				</li>
				<br />
				<li>
					<span className='about-span'>Functionality:</span> The app takes images submitted by the user and extracts three items from each photo's EXIF data. EXIF data is generated by most modern cameras and includes information like the make/model of the camera as well as the <span className='about-span'>date, time, and location</span> of the photo. That information is used to make an api request for historical weather data for the time and place that photo was taken. Each location is plotted on a google maps component, and users can sort their photos by any of the parameters included in the weather data, like precipitation, temperature, or wind speed.
					<br />
					Sometimes the camera can't determine the location, as it lost cellular or satellite connectivity - in this case, the photos will not be plotted because their location was not saved in the EXIF data.
				</li>
				<br />
				<li>
					<img src={require('../../src/loadingDemoCropped.gif')} style={{ width: '600px' }} alt='google maps component with pins across colorado' />
				</li>
				<br />
				<li>
					Another function I implemented was the ability to sort the photos by different weather attributes, so users could ask 'What was the hottest/rainiest/highest photo I took on that trip?' After selecting the parameter, the photo thumbnails are sorted, and the pins on the map change color according to their ranking by that parameter, making it easy to see patterns across the photos.
				</li>
				<br />
				<li>
					<div style={{ display: 'flex', marginLeft: '-50px', gap: '15px' }}>
						<img src={'/demo1.png'} style={{ width: '350px', alignSelf: 'center'}} alt='google maps component with gradient of pins from black to red' />
						<img src={'/demo2.png'} style={{ width: '350px', alignSelf: 'center'}} alt='google maps component with gradient of pins from black to red' />
					</div>
				</li>
			</ul>
		</div>
	)
}
